apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ticketing-crt
spec:
  secretName: ticketing-crt-secret
  dnsNames:
    - testengineering.co.nz
  issuerRef:
    name: ticketing-crt
    # We can reference ClusterIssuers by changing the kind here.
    # The default value is Issuer (i.e. a locally namespaced Issuer)
    kind: Issuer
    group: cert-manager.io
